backend:
  name: github
  repo: ai24news24-ai/sito-decap-cms
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "notizie"
    label: "Notizie"
    folder: "content/notizie"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Testo", name: "body", widget: "markdown" }
